### ISSUE TITLE
Source code for NDSEventTool

### ISSUE THREAD

**Issue by mrhappyasthma** [suloku/savegame-manager#14]
Would you be able to update the repo to include the source code for NDSEventTool?

I would like to edit it to include the unofficial event for English Pokemon Emerald "Old Sea Map". I have the .wc3 file for it, but this repository only seems to have the savegame-manager source code.

Thanks.

**Comment by suloku** [comment]
You are right, I was pretty sure I committed the changes, but seems I made them all local.
I'll try to commit today.

Btw, I'm not against you adding the english wc3, but please specify it's not an official event for no confusion

**Comment by mrhappyasthma** [comment]
Actually looking into it, seems they are on branch `mystery-event` but not merged into `master`.

https://github.com/suloku/savegame-manager/tree/mystery-event

**Comment by suloku** [comment]
Oh you are right, the code is in the branch. Wc3 files are in me.h as arrays.

**Comment by mrhappyasthma** [comment]
Sweet. Thanks!

**Comment by mrhappyasthma** [comment]
Sent a pull request to merge this back on to master. If that seems reasonable to you, feel free to approve: https://github.com/suloku/savegame-manager/pull/15
